spring:
  application:
    name: "store-service"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "myadmin"
    password: "myadmin"
    url: "jdbc:postgresql://localhost:5432/organization-service"
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082