server:
  port: 8084
spring:
  application:
    name: "terminal-telegram-bot-api"
  datasource:
    url: "jdbc:postgresql://localhost:5432/prodaja-desktop"
    username: "myadmin"
    password: "myadmin"
  banner:
    location: classpath:custom-banner.txt
    charset: UTF-8
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
