spring:
  application:
    name: "terminal-telegram-bot-api"
  datasource:
    url: "jdbc:postgresql://localhost:5432/organization-service"
    username: "myadmin"
    password: "myadmin"
  banner:
    location: classpath:custom-banner.txt
    charset: UTF-8
upload:
  folder:
    img: "/TERMINAL/img"
server:
  port: 8083